### PR TITLE
add publish pipeline

### PR DESCRIPTION
**Pull request by Q-Sharp**
Just updated the used action and added a new one: publish.yaml

The idea was to give you a way to manual release a new version of your nuget packages.

1.) building
2.) packing a nupkg
3.) uploading the new release 
   a.) on github
   b.) on nuget

Somehow the created nupkg is missing the source folder....
I tested the same command local with the same dotnet sdk version on Windows 10 and Ubuntu (wsl) and the source folder is correctly added to the generated pkg.
But on github actions it's always missing...

Maybe you have an idea what could be the problem here?

Also let me know if something like that is useful to you at all.

### CODE REVIEW

**Comment by Q-Sharp** [comment]
Addition to 3.) a.) and tagging a release in git

**Comment by damienbod** [comment]
@Q-Sharp Thanks for this. I have not had time to look at this yet, will get to this next week. 

Thanks for the PR

**Comment by Q-Sharp** [comment]
@damienbod  sure mate. It only has to create correct pkg's now 🥇 

Maybe @sayedihashimi can help us out here?

**Comment by sayedihashimi** [comment]
If you're trying to create a nupkg with templates, this repo should help https://github.com/sayedihashimi/sayedha.templates. You can use the template "templatepackcsproj" to create the csproj used to pack. You can see the build script I use to create the package at https://github.com/sayedihashimi/sayedha.templates/blob/main/build-nuget.ps1. 

Let me know if you have any questions.

**Comment by Q-Sharp** [comment]
I'm already using a template.csproj and if I try to run the dotnet pack command locally (on windows and on ubuntu) a valid npkg is created. But I try to use github actions for this and the created npkg file is more or less empty:

[Release 1.2.8 with empty npkg](https://github.com/Q-Sharp/Blazor.BFF.OpenIDConnect.Template/releases/tag/Release_1.2.8)

[github actions](https://github.com/Q-Sharp/Blazor.BFF.OpenIDConnect.Template/actions/runs/3081690947/jobs/4980523639)

image

Any ideas? @sayedihashimi

**Comment by sayedihashimi** [comment]
I'm really not sure. What I would recommend to start is to try to package this using WSL with ubuntu to see if that reveals any issues. Maybe there is some bug when building on that OS. I looked at the template csproj, and it looked like it had all the right things. It is kind of curious that the only files to make it in the package are the ones you have explicitly listed with `<Pack>True</Pack>`. One thing you could try is to add that metadata to all `Content` items by using `update`. For example https://stackoverflow.com/a/54173775/105999.

**Comment by Q-Sharp** [comment]
It all didn't help @sayedihashimi. But I found a solution. I'm using windows-latest now instead of ubunut-latest and that solved the problem.
I guess there is any kind of problem with ubuntu github actions version of this command, because on my local wsl ubuntu everything worked as expected.

@damienbod take a look and uncomment the publish to nuget lines but you have to add a secret with your nuget api key to the repo.

**Comment by sayedihashimi** [comment]
Sorry I couldn't help more. I'm not that familiar with GH Actions, but I'm happy you found a workaround.

**Comment by damienbod** [comment]
@Q-Sharp  @sayedihashimi 

Works great, thanks a million for this. 

@Q-Sharp  really great work, awesome, thanks

**Pull request merged**
